frontend:
  build:
    context: ./order-matching-frontend
  container_name: frontend
  restart: always
  ports:
    - "3000:3000"
  environment:
    - REACT_APP_SOCKET_URL=http://backend:3001
  depends_on:
    - backend
